multi-line steps

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,5 +12,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: Failed step
+        run: |
+          echo "I am such a failer"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
